apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git-server.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- guestbook.yaml

configMapGenerator:
  - name: nginx-conf
    files:
      - nginx.conf
generatorOptions:
  disableNameSuffixHash: true